version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_container
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: sergiopedretti
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    command:
      - "bash"
      - "-c"
      - |
        /usr/local/bin/docker-entrypoint.sh postgres \
        && psql -h localhost -p 5432 -U sergiopedretti -d app -f /docker-entrypoint-initdb.d/drop.sql
        && psql -h localhost -p 5432 -U sergiopedretti -d app -f /docker-entrypoint-initdb.d/create.sql
    ports:
      - "5432:5432"

volumes:
  postgres_data:
